language: node_js
node_js:
  - "node"
install:
  - cd ..
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-core.git iota-pico-core
  - cd iota-pico-core
  - npm link
  - cd ../iotaeco/iota-pico-api
  - npm link @iota-pico/core
  - npm install
script:
  - npm run dist
cache:
  directories:
    - "node_modules"
